gyunaev/birdtray

src/birdtray.pro, src/windowtools.cpp, src/windowtools_win.cpp, src/windowtools_win.h
This allows birdtray to hide / show / close the thunderbird window on Windows.
=> Add windowtools support for Windows

src/dialogaddeditaccount.ui, src/dialogaddeditnewemail.ui, src/dialogsettings.ui, src/main.cpp, src/resources.qrc
Previously, they all showed a default program icon.
=> Use the birdtray icon for all windows and dialogs

src/dialogsettings.ui
* Fixes a few minor typos in the settings UI
* Suggests a better title for the Settings dialog
=> Fix a few UI typos

.travis.yml, tools/qt-installer-windows.qs
Fix Travis not able to download Qt, which caused build failures.
=> Fix Travis compilation on Windows

.github/ISSUE_TEMPLATE/bug_report.md
Add an issue template for bug reports.
=> Add bug issue templates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Also add some icons to the template names, because a little bit of color never hurt.
(Go [here](https://github.com/gatsbyjs/gatsby/issues/new/choose) to see how it will look with the icons)
=> Add a feature request / enhancement issue template

src/birdtray.pro
This used to work, don't know what changed.
=> Fix qmake compile on Windows

src/colorbutton.cpp, src/colorbutton.h, src/morkparser.cpp, src/morkparser.h
As requested in [#161 (comment)](https://github.com/gyunaev/birdtray/pull/161#discussion_r347086177).
I also found tabs in `src/colorbutton.*`.
=> Convert tab indentations to space

src/autoupdater.cpp
=> Fix Qt backwards compatibility on Windows

src/res/com.ulduzsoft.Birdtray.appdata.xml, src/version.h
Update the verison to 1.7.0 for the new release.
=> Bump version to 1.7.0

src/translations/dynamic_nl.ts, src/translations/installer_de.ts, src/translations/installer_en.ts, src/translations/installer_nl.ts, src/translations/main_nl.ts
=> Added Dutch translation

CMakeLists.txt
This was an oversight on my part from #241.
=> Add nl translation to CMakeLists.txt

.github/workflows/main.yml
See jurplel/install-qt-action#27 for an explanation.
=> Temporary use ouuan/install-qt-action to work around the deadlock bug

.github/workflows/main.yml
This resolves issues when re-running a build.
=> Update the checkout action to v2

CMakeLists.txt, src/translations/installer_de.ts, src/translations/installer_en.ts, src/translations/installer_it.ts, src/translations/installer_nl.ts, src/translations/main_it.ts
This finishes the remaining issues with #253.
=> Finish Italian translation

installer/buildInstaller.bat
=> Allow opening of svg images on Windows

src/dialoglogoutput.cpp
It may improve log readability
=> Use monospace font for log window

src/birdtrayapp.cpp, src/main.cpp, src/settings.cpp, src/settings.h
=> Remove the `--debug` command line option

.github/workflows/main.yml
Partially revert commit 10eff850.
=> Re add the condition to only run the 'Create Release' workflow only if a tag was added

src/birdtrayapp.cpp, src/translations/main_de.ts, src/translations/main_en.ts, src/translations/main_it.ts, src/translations/main_nl.ts, src/utils.cpp, src/utils.h
=> Revert "Remove Util::decodeIMAPutf7 and the "decode" command line option"

contrib/rpm/birdtray.spec, src/res/com.ulduzsoft.Birdtray.appdata.xml
@gyunaev I think we should create the release today, we've waited long enough.
Closes #297.
=> Bump version to 1.8.0

src/res/translators.md
I think I've did all the steps to add the Portuguese translation, if something is missing, please let me know.
=> Updated translators.md

CMakeLists.txt, src/translations/installer_de.ts, src/translations/installer_en.ts, src/translations/installer_it.ts, src/translations/installer_nl.ts, src/translations/installer_pt.ts, src/translations/installer_ru.ts
@igorruckert I did the required changes for you. Closes #328, closes #330, closes #329, closes #327 and closes #323.
=> Finish the Portuguese and Russian translation

installer/installer.nsi
=> Don't save a language for the installer if installing in silent mode

src/translations/main_ru.ts
Corrected the ending in the word.
=> Small update main_ru.ts

src/translations/dynamic_de.ts, src/translations/dynamic_en.ts, src/translations/dynamic_es.ts, src/translations/dynamic_it.ts, src/translations/dynamic_nl.ts, src/translations/dynamic_pt.ts, src/translations/dynamic_ru.ts, src/utils.cpp
=> Fix the inbox not being translated

contrib/unreadhook/examplehook.sh, src/dialogsettings.cpp, src/dialogsettings.ui, src/settings.cpp, src/settings.h, src/translations/main_de.ts, src/translations/main_en.ts, src/translations/main_es.ts, src/translations/main_it.ts, src/translations/main_nl.ts, src/translations/main_pt.ts, src/translations/main_ru.ts, src/trayicon.cpp
Implemented a hook unread counter, allowing to invoke a process eachtime the unread count changes. This is for post-1.8.1 release since it adds new strings.
=> Hook unread counter

CMakeLists.txt, src/res/translators.md, src/translations/dynamic_tr.ts, src/translations/installer_de.ts, src/translations/installer_en.ts, src/translations/installer_es.ts, src/translations/installer_it.ts, src/translations/installer_nl.ts, src/translations/installer_pt.ts, src/translations/installer_ru.ts, src/translations/installer_sv.ts, src/translations/installer_tr.ts, src/translations/main_tr.ts
=> Turkish translation

src/translations/main_nl.ts
=> Updated Dutch translation

.github/workflows/codeql-analysis.yml
Looks like the Autobuild action is not compatible with CMake. We fix this by copying the relative steps for Ubuntu from the Build workflow.
=> Fix codeql-analysis workflow

CMakeLists.txt, src/translations/dynamic_fr.ts, src/translations/installer_de.ts, src/translations/installer_en.ts, src/translations/installer_es.ts, src/translations/installer_fr.ts, src/translations/installer_it.ts, src/translations/installer_nl.ts, src/translations/installer_pl.ts, src/translations/installer_pt.ts, src/translations/installer_ru.ts, src/translations/installer_sv.ts, src/translations/main_fr.ts
Note : I didn't check this translation into birdtray.
=> French translation

.github/dependabot.yml
=> Update the GithubAction workflows once a month

CMakeLists.txt, src/res/translators.md, src/translations/dynamic_zh_cn.ts, src/translations/installer_de.ts, src/translations/installer_en.ts, src/translations/installer_es.ts, src/translations/installer_fr.ts, src/translations/installer_it.ts, src/translations/installer_nl.ts, src/translations/installer_pl.ts, src/translations/installer_pt.ts, src/translations/installer_ru.ts, src/translations/installer_sv.ts, src/translations/installer_tr.ts, src/translations/installer_zh_cn.ts, src/translations/main_zh_cn.ts
=> Add Chinese translation

CMakeLists.txt, src/res/translators.md, src/translations/dynamic_el.ts, src/translations/installer_de.ts, src/translations/installer_el.ts, src/translations/installer_en.ts, src/translations/installer_es.ts, src/translations/installer_fr.ts, src/translations/installer_it.ts, src/translations/installer_nl.ts, src/translations/installer_pl.ts, src/translations/installer_pt.ts, src/translations/installer_ru.ts, src/translations/installer_sv.ts, src/translations/installer_tr.ts, src/translations/installer_zh_cn.ts, src/translations/main_el.ts
Hello
This pull request for adding the Greek translation
=> Add Greek [el] translation

src/unreadmonitor.cpp
Previously, the forceUpdateTimer was executed on the main thread. Because QTimers can only be started and stopped on the thread they belong to, this meant that changing the settings about the force unread timer did not apply, because the `slotSettingsChanged` function is called on the UnreadMonitor tread. So editing the timer did just print the following error to the log:
`QObject::startTimer: Timers cannot be started from another thread`
The setting would only really apply when Birdtray was restarted.
The fix is to let the mForceUpdateTimer be a child of UnreadMonitor. This causes the timer to be moved to the UnreadMonitor thread by the `moveToThread(this)` call in the constructor. The initial start of the timer is then moved to the run method, so it happens on the thread.
=> Move the forceUpdateTimer to the UnreadMonitor thread

.github/scripts/checkTranslation.py, src/translations/installer_zh_cn.ts, src/translations/main_zh_cn.ts
This gets rid of a bunch of ignored warnings in the Chinese translations.
=> Improved check translation script

src/dialogsettings.cpp, src/dialogsettings.ui, src/qtcomponents.cpp, src/qtcomponents.h, src/translations/main_cs.ts, src/translations/main_de.ts, src/translations/main_el.ts, src/translations/main_en.ts, src/translations/main_es.ts, src/translations/main_fr.ts, src/translations/main_it.ts, src/translations/main_nl.ts, src/translations/main_pl.ts, src/translations/main_pt.ts, src/translations/main_ru.ts, src/translations/main_sv.ts, src/translations/main_tr.ts, src/translations/main_zh_cn.ts
Following review and comments in #588
Following PR include following modifications :
* Rework of QTreeViewWithKeyEvents to use signal system of Qt
* Add tooltip to present new deletion based on keystroke
=> Refactor key press management in dialog settings

CMakeLists.txt, src/birdtrayapp.cpp
This got broken during the move to Qt6.
Closes #606.
=> Fix building the translations

.github/workflows/main.yml, installer/buildInstaller.bat
Fixes the CI to build the Windows installers.
=> Fix Windows installer CI build
