.gitignore
CMakeLists.txt
cmake/FindSQLite3.cmake

This allows to build the project with cmake.
It also allows to import and edit the project with [Clion](https://www.jetbrains.com/clion/).
If you accept this, all new source files that will be added to the project in the future will have to be added to the birdtray.pro as well as to the CmakeList.txt file.
However, in my opinion this is not to much work to do (it's just appending to a variable in both files) and is worth the benefits of supporting a well used build system.

Add support for building the project with cmake

---

src/trayicon.cpp

Previously, Birdtray would leave a "ghost" tray icon behind after closing.

Fix tray icon still visible after birdtray closes on Windows

---

src/settings.cpp
src/settings.h
src/trayicon.cpp
src/utils.cpp
src/utils.h

Previously on first start, Birdtray would fail to start Thunderbird on Windows.
This also adds support for shell like expansion of the path, which expands variables and `~`.
Additionally, paths which contain spaces are handled as well.

Use the correct default thunderbird path on Windows

---

src/windowtools_win.cpp
src/windowtools_win.h

On windows, use a [window hook](https://docs.microsoft.com/windows/desktop/WinAuto/registering-a-hook-function) to detect when the Thunderbird window is minimized instead of a check every 250 milliseconds.
This reduces CPU usage and makes the hiding of the window instant.

Use a window hook to detect the minimize

---

CMakeLists.txt

This tells cmake to compile BirdTray as a win32 GUI executable, suppressing the command prompt.

Fix opening a command prompt when compiling with cmake on Windows

---

src/birdtray.pro

Sorry, I forgot to add that to #69.

Add metadata for the Windows executable generated by the Qt project

---

src/main.cpp
src/morkparser.cpp
src/settings.cpp
src/utils.cpp
src/utils.h

Previously, if birdtray was started on a platform where Qt has no system tray support, it would just abort without a message. A user would probably assume, birdtray had crashed.
This adds an error dialog displaying the message before passing it to qFatal.

Show an error dialog when we encountered a fatal error

---

installer/buildInstaller.bat

This removes all dlls needed by Qt to support additional image formats, reducing the size of the installer and the installation. `qico.dll` is excluded, because it is needed to display the birdtray window icons. Png files are still supported, because Qt does not require an additional dll to load them. For additional info, see [here](https://github.com/gyunaev/birdtray/pull/71#issuecomment-475914098).

Remove unneeded image format dlls

---

src/dialogsettings.cpp
src/modelaccounttree.cpp
src/modelaccounttree.h

If a user had no accounts configured for monitoring and switched the method to parse unread notifications from Mork to Sqlite, we would display a dialog asking them to delete all old accounts and then crash, after the user clicked continue.
These changes ensure that we don't crash and that we don't show the dialog if we don't have any accounts to delete.

Fix a crash when trying to clear accounts when we have no accounts

---

src/databaseaccounts.cpp
src/databaseaccounts.h
src/databaseunreadfixer.cpp
src/databaseunreadfixer.h
src/dialogsettings.cpp
src/dialogsettings.h
src/unreadcounter.cpp

* Prevent appending an additional slash (This is how it was before: `C:/path/to/folder\`).
* Display the path with the native file separators (was always `/` before).
* Centralize the knowledge about `global-messages-db.sqlite` in DatabaseAccounts. This reduces code duplication.

Cleanup sqlite database path handling

---

src/dialogaddeditaccount.cpp
src/dialogaddeditaccount.h
src/modelaccounttree.cpp
src/settings.cpp

If the sqlite parser failed to parse any accounts from the database, it would not fill the combobox in the AddAccountDialog. As a result, if the user hit `Ok`, an account was saved to the settings with an empty URI, which causes problems when trying to search the database for the account (See #77).
This prevents the user from adding an "empty" account and removes such accounts from the settings, when we load them.

Fix empty account URIs

---

src/birdtrayeventfilter.cpp
src/trayicon.cpp
src/trayicon.h

This fixes a regression for Windows which I introduced in #76, that caused Birdtray to exit, if the user closed a Birdtray-window (e.g. the Settings) with the red X on the window decoration.
We also now properly show and (depending on the settings) close the Thunderbird window when we are asked to quit by the installer (or taskkill).

[Windows] Fix closing Birdtray on window close

---

src/trayicon.cpp
src/trayicon.h

Looks like older versions of Qt (<= 5.5) don't like connecting QApplication::quit directly to a menu action.
See https://travis-ci.org/gyunaev/birdtray/jobs/521692228

Fix compilation for Qt5.5

---

src/dialogsettings.cpp
src/main.cpp
src/settings.cpp
src/settings.h
src/trayicon.cpp
src/trayicon.h

This uses the QCommandLineParser and adds the `--settings` and `--reset-settings` or `-r` command line options.
We also get a version and help options for free:
```console
me@myshell:~$ birdtray.exe --version
birdtray 1.5
me@myshell:~$ birdtray.exe --help
Usage: birdtray.exe [options]
A free system tray notification for new mail for Thunderbird
Options:
-?, -h, --help              Displays this help.
-v, --version               Displays version information.
--dump-mork <databaseFile>  Display the contents of the given mork database.
--decode <string>           Decode an IMAP Utf7 string.
--settings                  Show the settings.
-r, --reset-settings        Reset the settings to the defaults.
-d, --debug                 Enable debugging output.
```
On windows, it will display a dialog …

Add --settings and --reset-settings as command line options

---

README.md

The Debian package names don't work on Buster. I changed them to working values.

Changed debian package names

---

installer/Utils.nsh
installer/installer.nsi
installer/makeUninstallList.nsi

This will delete only the files that were installed during installation. If the user manages to save another file into the installation directory of Birdtray, the uninstaller won't delete it.
The installer also now handles replacing an existing installation, if the uninstaller is missing.

Make it harder to accidentally delete files on uninstall

---

src/unreadcounter.cpp
src/unreadcounter.h

It previously always choose the default color.

Fix account color selection for the sqlite parser

---

src/dialogsettings.cpp
src/dialogsettings.h

This caused the accounts list of the Add-/Edit-dialog to be empty, when the user first selected the profile path.
The user would have to close the settings dialog and reopen it again to see the list of available accounts.

Fix sqlite-db handler not updating the account list when first selected

---

src/dialogsettings.cpp
src/dialogsettings.ui
src/settings.cpp
src/settings.h

A value greater than 99 will cause a crash.
See https://doc.qt.io/archives/qt-4.8/qfont.html#Weight-enum

Prevent crash from font boldness exceeding 99

---

.gitignore
src/birdtray.pro

When processing the resource file the `version.h` was not found.
This also excludes `birdtray.pro.user*` from git which are created by the QtCreator.

Fix building the project with the QtCreator in Windows

---

tools/qt-installer-windows.qs

Qt changed their online installers, which caused the installation of Qt on the windows containers on Travis to fail:
https://stackoverflow.com/questions/58311016/qt-installer-scripting-api-cant-select-latest-qt-version-in-online-installer

Fix installing Qt in the Windows containers on Travis

---

CMakeLists.txt
src/autoupdater.cpp
src/autoupdater.h
src/birdtray.pro
src/dialogsettings.cpp
src/dialogsettings.h
src/dialogsettings.ui
src/main.cpp
src/settings.cpp
src/settings.h
src/trayicon.cpp
src/trayicon.h
src/updatedialog.cpp
src/updatedialog.h
src/updatedialog.ui
src/updatedownloaddialog.cpp
src/updatedownloaddialog.h
src/updatedownloaddialog.ui

This adds an update checker that checks for a new version of Birdtray. It can be run manually through the settings or configured to run automatically when Birdtray starts. If a new update is found, a dialog is displayed showing the release notes and a download button.
On non-Windows platforms, a click on the download button opens the [releases page](https://github.com/gyunaev/birdtray/releases).
On Windows, if found the correct installer will be downloaded. Once the installer is downloaded and the user confirms the update, the installer is started and Birdtray closes.
The information about the new releases are fetched via the [Github releases api](https://developer.github.com/v3/repos/releases/). As such, the update checker will only detect a new update, once a Github release is created. …

Update checker and auto updater

---

src/trayicon.cpp

[QFontMetrics::width](https://doc.qt.io/qt-5/qfontmetrics-obsolete.html#width) was deprecated in Qt 5.11.

Fix the deprecation warning of QFontMetrics::width for Qt >= 5.11

---

src/dialogsettings.cpp

With Qt 5.12 the current master doesn't list any files. The problem is that the `filter` parameter is valid and cannot be parsed by Qt ([see reference](https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileName)).
This PR fixes it.

Fix open image file dialog

---

.travis.yml
installer/buildInstaller.bat
src/autoupdater.cpp
src/dialogsettings.cpp

The Windows installer now bundles the required OpenSSL libraries.
I also noticed, that when the libraries were missing, only the first network request made would generate an error. All request made after that would just never complete, without sending any signals. We now detect that and display a user friendly message suggesting that OpenSSL might not be installed. Fixes #137

Bundle the required OpenSSL libraries in the installer

---

src/dialogsettings.cpp
src/dialogsettings.h
src/dialogsettings.ui
src/settings.cpp
src/settings.h
src/trayicon.cpp

This lets the user add a border around the unread mail number in the system tray. This improves readability, because it increases the contrast of the text to the background image. The user can configure the color and width of the border, as well as disable the border entirely.
Without border:  ![image](https://user-images.githubusercontent.com/6966049/67433583-ab7fad80-f5e8-11e9-8b76-2cb609b0bd35.png)
With border (white, 30% width): ![image](https://user-images.githubusercontent.com/6966049/67433534-986cdd80-f5e8-11e9-80ca-986197c66aae.png)
We also change the default notification color from radioactive green to blue. I don't think anybody kept the green.
Additionally, I added `Off` and `Fastest` labels to the blink speed slider, because it isn't clear at first sight, what the slider does. …

Add an optional border to the unread counter

---

src/dialogsettings.cpp
src/modelaccounttree.cpp
src/modelaccounttree.h

This improves the accounts list in the `Monitoring` tab.
* If the the Mork parser is selected, the list now longer displays the path to the mork file, but the mail account name and the mail folder.
* The first row now auto resizes to always show the full account name and folder.
* There is now always an element of the selected, so the `Edit` and `Remove` buttons always work.
* Remove the `uses this color` text. It was unnecessary and hard to read or unreadable, if a dark color was selected.
* The selected notification color is now always visible, even when the item is selected.
* Editing an item now only opens a dialog to choose a new color. To change the selected account and folder, remove the item and add a new one.
Images:
<details>
<summary>Ubuntu (Before vs. after):</summary> …

Improved accounts list

---

src/dialogaddeditnewemail.cpp
src/dialogaddeditnewemail.h

The `DialogAddEditNewEmail::accept` was called twice, once because of the connected `QDialogButtonBox::accepted` and once because it overwrites `QDialogButtonBox::accept`.

Fix displaying the error message twice in the Add/Edit "New Email" entries dialog

---

src/dialogaddeditnewemail.cpp
src/dialogaddeditnewemail.ui
src/dialogsettings.cpp
src/modelnewemails.cpp
src/modelnewemails.h

This improves two things:
* An entry is now always selected in the `Menu entry item`-list. As a result, the `Edit` and `Remove` buttons now always work.
* Rearranges the `dialogaddeditnewemail` dialog so it is easier to understand.
<details>
<summary>Ubuntu (Before vs. after)</summary>
</details>
<details>
<summary>Windows (Before vs. after)</summary>
</details>

Improvements to the "New Email" settings UI

---

src/setting_newemail.cpp

This prevents the user from specifying other command line options.
For example, you could write `',subject='test` as the email text to set `test` as the subject.
This replaces all occurrences of single quotes (`'`) with the [unicode prime character](https://www.compart.com/en/unicode/U+2032) (`U2032`, `′`). This solution isn't ideal, because the characters don't look exactly alike, and anybody receiving the mail in a mail client without utf-8 support will see a tofu or question mark symbol. But according to [Mozillas command line syntax rules](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options#Syntax_Rules) there is no way to escape a single quote in the argument values.

Add support for the message in mail templates and escape the command line

---

src/dialogaddeditnewemail.ui
src/trayicon.cpp

This adds a new `Blank` action, that allows to create an empty email even if there are templates defined:
This also fixes the tab ordering in the "New Email" entry dialog. pressing tab no longer directly jumps to the message box, but allows to edit the recipient and subject as well:

Add a "Blank" entry to the "New Mail" submenu

---

src/birdtrayapp.cpp

This fixes the TODOs in the `BirdtrayApp` class.
**This is a change in behaviour!**
Previously, both the `dump-mork` and `decode` command would return `1` (`EXIT_FAILURE`).

Return EXIT_SUCCESS for the dump-mork and decode commands

---

src/birdtray.pro

`CONFIG += lrelease` is not supported on versions of qmake prior to Qt 5.12.
As a result, the `*.qm` files would not be generated from the `*.ts` files and the copy directive would fail.
This replaces the `lrelease` and the undocumented `file_copies` with another "unofficial" way, but at least this time it is [documented](https://wiki.qt.io/Automating_generation_of_qm_files).

Fix qmake compilation for the translations, fixes #159

---

CMakeLists.txt

This adds a `clean_translations` target to cmake to make it easy to remove obsolete translation entries.
The target must be invoked manually by calling `cmake --build . --target clean_translations`.

Add clean_translations target

---

.travis.yml
CMakeLists.txt
src/autoupdater.cpp
src/birdtrayapp.h
src/dialogsettings.cpp
src/dialogsettings.h
src/mailaccountdialog.cpp
src/morkparser.cpp
src/processhandle.h
src/updatedownloaddialog.cpp
src/updatedownloaddialog.h
src/windowtools_win.cpp

This can prevent possible errors which are indicated by the warnings and keeps the code robust.

Enable "Warning as errors" when compiling

---

.gitignore
README.md
installer/StrUtils.nsh
installer/Utils.nsh
installer/buildInstaller.bat
installer/installer.nsi
installer/makeInstallerTranslations.nsi
installer/makeUninstallList.nsi
src/translations/installer_de.ts
src/translations/installer_en.ts
tools/qt-installer-windows.qs

This adds the ability to translate the Windows installer. The user will be asked to choose a language when the installer/uninstaller starts.
The translations are generated from the `src/translations/installer_*.ts` files.
To add a new translation, one has to copy an existing `installer_*.ts` file and and change the 
`message` entry with the `__LANGUAGE_NAME__` `source`. The `translation` value for this indicates the target language and must be the name of one of the [NSIS translation files](https://sourceforge.net/p/nsis/code/HEAD/tree/NSIS/trunk/Contrib/Language%20files/) without the file extension. E.g. `German.nlf` becomes:
```xml
<message>
<source>__LANGUAGE_NAME__</source>
<translation>German</translation>
</message>
```

Add translations for the Windows installer

---

src/trayicon.cpp
src/trayicon.h
src/unreadcounter.cpp
src/unreadcounter.h

This fixes the error that caused #171:
`QThread: Destroyed while thread is still running`

Prevent UnreadCounter from being deleted while still running

---

src/mailaccountdialog.cpp

When I read #166 I noticed that the new mail account dialog won't find the email accounts in the `webaccountMail` folder. This fixes that and assumes that any folders ending in `Mail` in the profiles directory can contain email accounts.

Search for email accounts in any *Mail sub directory of the profile

---

.gitignore
installer/Utils.nsh
installer/installer.nsi
installer/makeTranslationsList.nsi
src/translations/installer_de.ts
src/translations/installer_en.ts

Adds the ability to select which translations should get installed from the Windows installer.

Allow to select the translations to be installed with Birdtray

---

src/trayicon.cpp
src/unreadcounter.cpp

The `TrayIcon::unreadCounterError` callback may be called multiple times (e.g. if multiple `.msf` files are not watchable).

Prevent crash when reporting multiple errors from UnreadCounter

---

src/dialogsettings.ui

This should be helpful for everybody who has configured multiple accounts.
Before:
After:

Allow the settings to expand with the window

---

src/dialogsettings.cpp
src/dialogsettings.h
src/dialogsettings.ui
src/settings.cpp
src/settings.h
src/translations/main_de.ts
src/translations/main_en.ts
src/trayicon.cpp
src/utils.cpp
src/utils.h

When installed via flatpak, Thunderbird can not be started with the path to the Thunderbird executable. It has to be started via the `flatpak-spawn` command.
Birdtray will prefer the native Thunderbird executable over the flatpak command, if it is present.
This also changes how the user can edit the Thunderbird command in the `Advanced` settings tab: Instead of entering the command in a text editor, the command and arguments can now be entered in a small dialog with a list view, to clearly separate the arguments from another.
<details>
<summary>Pictures</summary>
</details>

Support for starting flatpack Thunderbird

---

CMakeLists.txt
src/trayicon.cpp
src/unreadmonitor.cpp
src/unreadmonitor.h

This is a better fix than #174. It could still sometimes crash when Birdtray was exiting.
We no no longer move the `QThread` object to the thread. This causes the destructor tobe executed on the main thread, allowing us to wait for the thread to exit before continuing destruction the object.
I also renamed the source file so it matches the class name.

Better fix for delete while still running error

---

CMakeLists.txt

The Cmake target requires the Qt linguistic tools to be present. Since commit 57e805660eba41d2771c71447129017367f9fe82, the QtLinguisticTools are optional, so we only define the target if we find them.

Guard the clean_translations target behind if(Qt5LinguistTools_FOUND)

---

src/unreadmonitor.cpp

I'm not sure what his code do does. As of right now, without this change, the `else` block seems to do nothing, because `rescanall` is initialized to `false` a few lines above.
I think the intention here is to add the path to the filesystem watcher if it is not already watched, is that right? If so, this could be simplified.
@gyunaev Could you please clarify what this code is intended to do?

Fix potentially not watching mork files

---

src/mailaccountdialog.cpp
src/modelaccounttree.cpp
src/translations/dynamic_de.ts
src/translations/dynamic_en.ts
src/translations/main_de.ts
src/translations/main_en.ts
src/utils.cpp
src/utils.h

This fixes #194.
We allow to select `.msf` files in mail subfolders (folders ending with `.sbd`).
We should merge this before we make a new release.

Allow to select msf files in mail subfolders

---

src/mailaccountdialog.cpp
src/mailaccountdialog.h

This allows to automatically select all detected `.msf` files in an account by selecting a checkbox at the account item.

Add recursive selection of mail folders to monitor

---

src/mailaccountdialog.ui
src/translations/main_de.ts
src/translations/main_en.ts

Add the missing German translations.
I also found a string in the `MailAccountDialog` that was not translated.

Update German translations

---

src/dialogsettings.cpp
src/dialogsettings.ui
src/settings.cpp
src/settings.h
src/translations/main_de.ts
src/translations/main_en.ts
src/trayicon.cpp
src/trayicon.h

This implements @Mintulix idea from #191 to add an option to ignore unread emails that already exist when Birdtray starts.
This is disabled by default. It can be enabled via a settings in the monitoring tab:
<details>
<summary>Image</summary>
</details>
@Mintulix Can you please test that this still works as you intended?

Add option to ignore unread mails at startup (by @Mintulix)

---

CMakeLists.txt
src/modelaccounttree.cpp
src/translations/main_de.ts
src/translations/main_en.ts
src/trayicon.cpp
src/trayicon.h
src/unreadmonitor.cpp
src/unreadmonitor.h

Previously, we showed a red `X` in the icon, if the parsing of one account failed, even if we could parse the unread count from other accounts.
We now don't abort the parsing process, if only one account couldn't be parsed. If a problem occurs, we show an exclamation mark in the icon:
Additionally, a tooltip is added with the problem description:
<details>
<summary>Problematic accounts are also marked in the settings.</summary>
</details>
If anybody has a better color combination for the exclamation mark, let me know. I'm not an artist and this is the best I could come up with that was still readable on the small icon.

Show warnings about problems parsing mail accounts as a tooltip on the tray icon

---

README.md

This PR simply elaborates in the README as to where the Birdtray configuration file is saved, to avoid confusion since the naming is unexpected.

Elaborate confugration file location in README

---

src/settings.cpp
src/settings.h
src/translations/main_de.ts
src/translations/main_en.ts
src/trayicon.cpp

This closes #216. The new `Don't ask again` button allows to disable the dialog.

Add a "Don't ask again" button to the "No accounts configured" dialog

---

src/birdtrayapp.cpp
src/birdtrayapp.h
src/translations/main_de.ts
src/translations/main_en.ts
src/trayicon.cpp
src/trayicon.h

This allows only one instance of Birdtray to be running at any given time (preventing situations like #157).
The details of the implementation were discussed in #209. It was tested with Windows 10 and Ubuntu 18.04.
The second instance will exit, once it passes its arguments to the first instance.
This makes it possible to control the first instance of Birdtray by starting the second instance with a command, e.g. to toggle the Thunderbird window (closes #48).
The following new commands were added (they currently only work if another Birdtray instance is already running):
* `--show`: Shows the Thunderbird window.
* `--hide`: Hides the Thunderbird window.
* `--toggle`: Shows the Thunderbird window if it was hidden, hides it otherwise.
The `--settings` command can now also be used to display …

Only allow one one Birdtray instance

---

src/windowtools_x11.cpp

According to the [```XQueryTree``` documentation](https://tronche.com/gui/x/xlib/window-information/XQueryTree.html) it is the responsibility of the caller to free the list of children windows.
The same goes for the data parameter of [```XGetWindowProperty```](https://tronche.com/gui/x/xlib/window-information/XGetWindowProperty.html).
This should fix #219.

Fix memory leaks in windowtools_x11.cpp

---

src/birdtrayapp.cpp

I propose to add a `-thunderbird` suffix to the name of the three command line options, to prevent confusion about their meaning. This shouldn't really affect anybody, since these commands were added only two days ago.
`--toggle` → `--toggle-thunderbird`
`--show` → `--show-thunderbird`
`--hide` → `--hide-thunderbird`

Clarify the show, hide and toggle command line options

---

src/dialogsettings.ui

Fix misaligned thunderbird command line input not being aligned to the other input:
Also fixes the order in which the `<Tab>` key traverses the widgets in the settings dialog.

Fix tab traversal order and small aligment issue in settings dialog

---

src/autoupdater.cpp
src/autoupdater.h
src/dialogsettings.cpp
src/dialogsettings.h
src/dialogsettings.ui
src/translations/main_de.ts
src/translations/main_en.ts
src/trayicon.cpp
src/trayicon.h

This adds a visual feedback to the advanced settings tab if no update was found.

Add a "No new update" indicator to the advanced settings page

---

src/birdtrayapp.cpp

This mainly fixes an issue on Linux, where the commands sometimes wouldn't be send to the main Birdtray instance, because the second instance quit too fast. This fixes this by waiting for the data to be send before quitting.
This also uses the correct function to close the socket and closes the server before destructing the rest of the attributes. The latter wasn't really a problem, because the event loop always exits before the Destructor is called.

Fix commands between Birdtray instances sometimes not send

---

src/dialogsettings.cpp
src/dialogsettings.ui
src/settings.cpp
src/settings.h
src/translations/main_de.ts
src/translations/main_en.ts
src/trayicon.cpp

Resolves #96. This adds a new option in the advanced tab, which is disabled by default.
If enabled, the Birdtray system icon is hidden, if no new mails are detected. It will also be hidden if the user uses the snooze feature, is that ok with you @gyunaev?
If the Birdtray icon is hidden, one can access the setting to turn off the option by starting a second instance of Birdtray with the `--settings` parameter. Note that just starting Birdtray without a parameter does nothing.
<details>
<summary>New setting in the advanced tab</summary>
</details>

Add setting to hide the Birdtray icon if no new mail is present

---

src/mailaccountdialog.cpp
src/mailaccountdialog.h
src/mailaccountdialog.ui
src/translations/main_de.ts
src/translations/main_en.ts

This improves the AddAccount dialog added by #145. Issues like #229 and #218 showed that the users where confused by the dialog being split into three parts, especially if the first two pages were skipped because Birdtray found empty Thunderbird profiles at the standard locations.
The new Dialog only consists of a single page, which allows to enter the Thunderbird profiles directory and select the mail folders to add. Because everything is on one page, the user can immediately see if the path is wrong. We also allow the user to input a path to a specific profile directory and automatically fix it (closes #206).
The new dialog also adds the ability to simultaneously add mail folders from different Thunderbird profiles.
<details>
<summary>Images</summary>
</details>

Improve the AddAccountDialog

---

src/dialogsettings.cpp
src/settings.cpp
src/settings.h

Fix inconsistent drawing of unread counter across different sizes of icons by
scaling icons to a predefined size.
In case of small icons (24x24, 32x32), unread count and border may be rendered incorrectly.
In addition, default icon size was used for the custom unread icon, so it caused image to be either too small or too big.
This solution scales an icon to a fixed size (original 128x128 is used) before drawing it. It may be an overhead, but it should work with existing configurations.
However I have a different solution [here](https://github.com/dvalter/birdtray/tree/icon-scaling-fix-v2), which scales icons before applying them to Settings from DialogSettings. The only downside I see is requirement for user to re-apply settings for changes to take effect.

Make tray icon size consistent

---

CMakeLists.txt
README.md

I recently added two pages to the Github wiki to help people who want to add new translations for Birdtray:
* [Add a new translation](https://github.com/gyunaev/birdtray/wiki/Add-a-new-translation)
* [Edit an existing translation](https://github.com/gyunaev/birdtray/wiki/Edit-an-existing-translation)
This pull request replaces the old help text in the README with links to the new pages.

Link to the new wiki pages for information about how to add new translations

---

src/dialogsettings.cpp

Change signal-slot connection order to prevent from loading accounts list before parser is configured on start of the settings window.

Stop showing database access error when Mork is already 

---

.github/workflows/main.yml
CMakeLists.txt
src/morkparser.cpp
src/morkparser.h
src/unreadmonitor.cpp
tests/.gitignore
tests/CMakeLists.txt
tests/deps/GTest/CMakeLists.txt
tests/deps/GTest/CMakeLists.txt.in
tests/res/0_Unread_Trash.msf
tests/res/1_Unread_Filter.msf
tests/res/6_Unread_Inbox.msf
tests/src/TestResources.cpp
tests/src/TestResources.h
tests/src/test_morkparser.cpp

This pull request adds unit tests 🎉. It is based on top of #257, which is why it also includes the changes for it.
In order to use the same compiled code in the Birdtray executable and the test executable, we now compile the main Birdtray code (everything except `main.cpp`) as a static library and link that with the two executables.
The tests are disabled by default. One needs to add the command line parameter `-DBUILD_WITH_TESTS=ON` when configuring the project with Cmake to enable the test. Doing so will add a `run_tests` target that can be used to compile and execute the tests.
We use [GTest](https://github.com/google/googletest) as the testing framework. If it is not installed on the system, it will be automatically downloaded by Cmake.
Currently, there is only one unit test that …

Add unit test(s)

---

src/morkparser.cpp
src/morkparser.h
src/unreadmonitor.cpp

While working on #245 I noticed that the `numNewMsgs` (`A2`) property was sometimes read incorrectly. One example of this was the following mork file, which I generated with Thunderbird and a test account.
<details>
<summary>The example mork file</summary>
```mork
// 
< <(a=c)> // (f=iso-8859-1)
(B8=viewFlags)(B9=viewType)(BA=columnStates)(BB=MRUTime)
(BC=sortColumns)(BD=customSortCol)(80=ns:msg:db:row:scope:msgs:all)
(81=subject)(82=sender)(83=message-id)(84=references)(85=recipients)
(86=date)(87=size)(88=flags)(89=priority)(8A=label)(8B=statusOfset)
(8C=numLines)(8D=ccList)(8E=bccList)(8F=msgThreadId)(90=threadId)
(91=threadFlags)(92=threadNewestMsgDate)(93=children)
(94=unreadChildren)(95=threadSubject)(96=msgCharSet)
(97=ns:msg:db:table:kind:msgs)(98=ns:msg:db:table:kind:thread) …
```

Fix parsing mork files with changesets

---

.gitignore
installer/buildInstaller.bat
installer/installer.nsi
src/translations/installer_de.ts
src/translations/installer_en.ts
src/translations/installer_nl.ts

With #233 now merged, a user might need to to start Birdtray with the `--settings` argument to be able to access the settings. Especially on Windows, not all users will know how to do that.
This pull request adds a link to the Birdtray folder in the start menu that can be used to open the Birdtray settings.

Add a link to the Birdtray settings from the Windows start menu Birdtray folder

---

src/dialogsettings.cpp
src/translations/main_de.ts
src/translations/main_en.ts
src/translations/main_nl.ts

This adds a debug / advanced dialog in the monitoring tab of the settings, that lets the user add any mork file anywhere as a watched account.
The advanced "Add mail accounts" dialog added by #145 was a nice improvement in terms of usability and user interface, but it took away the ability to freely select any mork file. And we know there will always be someone with mork files in a directory that we have not accounted for (like #195 and #167). The new dialog will readd that flexibillity.
To prevent an unexperienced user from accidentally stumbling into the dialog, you will need to press `<Shift>` and `<Control>` while clicking on the `Add` button to open the dialog.
@gyunaev Should I add a tooltip to the `Add` button that describes how to access the dialog?

Add a debug/advanced dialog to add any mork file for watching

---

installer/installer.nsi
src/translations/installer_de.ts
src/translations/installer_en.ts
src/translations/installer_nl.ts

A Windows bug causes the uninstaller to always be started with admin rights when uninstalling from the `Apps and Features` setting page. That caused the uninstallation of per-user installations to fail, because the unistaller looked in the `%Appdata%` folder of the admin account instead of the `%Appdata%` folder of the user ([Original issue description on the `NsisMultiUser` library](https://github.com/Drizin/NsisMultiUser/issues/6)). Closes #268.
To fix this we detect if there is no installation for the current user if we are the admin. In that case we ask if the user wants to restart the uninstaller without admin permissions.

Fix error message when uninstalling a local user installation on Windows

---

.github/workflows/main.yml

We now cache Qt on Github Actions, which improves the build time:
This also reverts #255, as the `jurplel/install-qt-action` seems to have stabilized.

Cache Qt on Github Actions

---

.github/workflows/main.yml
CMakeLists.txt
installer/Utils.nsh
installer/buildInstaller.bat
installer/getExeArch.nsi
installer/makeInstallerTranslations.nsi
installer/makeTranslationsList.nsi
installer/makeUninstallList.nsi

With this pull request, we can automatically create a **draft** release (that is hidden to non project maintainers) here on Github that contains prebuilt installers for Win x86 and x64. We just need to push a tag with the following pattern `v[0-9]+\.[0-9]+\.[0-9]+` (e.g. `v1.8.0`). This means this can only be done by someone with direct access to this repository, or when someone merges a pull request with the tag. A git push to a pull request should not be allowed to create a draft release, because it will have a `github.event_name` = `pull_request`. We should test this though after the merge to make sure.
We also now require a Cmake `3.14` for Windows users that want to use the cmake install target. That is probably not affecting a single person.

Add deployment via Github Actions

---

installer/Utils.nsh
installer/installer.nsi
src/translations/installer_de.ts
src/translations/installer_en.ts
src/translations/installer_it.ts
src/translations/installer_nl.ts

On a freshly installed Windows machine with no other programs, there will not be a C++ runtime and Birdtray will fail to start. The C++ runtime is shared by all programs on a Windows PC. If you install any other program (e.g. `Chrome` or `Firefox`), most of them will install the C++ runtime. That is why this is not a big problem and almost nobody encountered it, but it caused #220.
The installer for `1.7.0` contained an installer for the C++ runtime, but never installed it. Because the runtime installer made up a significant portion of the size of the Birdtray installer (~10Mb, 50% of the installer) and it is never used by 99.9% of the people using the installer, I decided the best option is to not include the C++ runtime installer in the Birdtray installer. Instead display a message and …

Detect missing C++ Runtime on Windows

---

src/main.cpp

Previously, it was not possible to view the debug output of Birdtray on Windows without attaching to the process with a debugger. On Windows, a program can either be compiled as a GUI application or a command line application. A command line application will automatically send its output to an attached console, but will also automatically create a console if it is started without one, meaning that Birdtray would open a cmd window if it was started. Because of this Birdtray is compiled as a GUI application, which doesn't create a console, but also doesn't automatically attach to one.
We now attach to the parent console, if there is one and if the `--debug` parameter was specified.
This means that the output is now visible on the console (closes #244), but unfortunately the command line …

Attach to the parent console if the --debug parameter is present on Windows

---

src/trayicon.cpp

This fixes the following warning:
`QSystemTrayIcon::setVisible: No Icon set`

Fix a Qt warning on startup

---

src/modelaccounttree.cpp

This removes the ability to watch the same mail folder multiple times. Fixes #231.
This bug was possible, because we store the information about the number of watched folders twice in the settings; Once as the actual data (`accounts/accountX[Color|URI]`) and once as a number (`accounts/count`).
The duplication of information is what allowed this bug, which is why this pull request removes the `accounts/count` value, so the actual data is the single source of truth. However, we still read the `accounts/count` for old installations, to keep backwards compatibility.

Fix duplicated watched mail folders

---

README.md
src/log.h
src/processhandle.cpp
src/trayicon.cpp
src/utils.cpp
src/utils.h

Sorry, this pull request contains a couple of small changes that are not really related to each other. But they all felt to small to create a separate pull request for each of them.
This pull request changes the following:
* Fix the path to the Birdtray config on Windows in the README.
* Use only push events from master for the Github Actions badge. Previously, if a pull request was made from the master branch of a fork to this repository, the commits on the pull request would affect the badge.
* Use the Qt attributes from `Utils::fatal` and `Utils::debug` that you missed when you reimplemented the functions in `Log`.
* Remove `Utils::getThunderbirdUpdaterName`, because the function is never used on non-Windows platforms.

Fix the config path for Windows and small improvements

---

src/birdtrayapp.cpp
src/log.cpp
src/log.h

Add -l/--log CLI option (higher priority) and checkbox to choose
where to write Birdtray logs.
In some cases (i.e. debugging or automated log collection) having log written to stdout, stderr or file may be significantly more convenient.

Add options for console log output

---

.github/workflows/main.yml
src/updatedialog.cpp
src/updatedialog.ui
src/utils.cpp
src/utils.h
tests/CMakeLists.txt
tests/src/test_utils.cpp

Qt version from 5.14.0 onwards support displaying markdown text.
Use this feature when compiling with an adequate Qt version and display the changelog as markdown.
On older Qt versions, we convert the markdown to a pure text form as best as possible:
To take advantage of the markdown feature, we bump the newest Qt on Github Actions to 5.14.1.

Display the changelog as markdown on Qt 5.14.0+

---

src/dialogsettings.cpp
src/dialogsettings.h
src/dialogsettings.ui
src/res/translators.md
src/resources.qrc
src/translations/main_de.ts
src/translations/main_en.ts
src/translations/main_it.ts
src/translations/main_nl.ts

This adds a new dialog that can be accessed via the `About` tab in the settings. The dialog lists everybody that added or contributed to a translation of Birdtray. We keep those contributors at the top who agreed to get notified before every release to keep their translation updated. This also gives us a list of who to contact prior to a new release. We also don't need to ask new contributors if they want to get notified before a release, they can decide for themself when they add their names to the list. And if someone no longer wants to actively maintain a translation, they can move their name to the second list.
<details>
<summary>Images</summary>
</details>
<details>
<summary>Older versions of Qt don't support displaying markdown</summary>
</details>
@Vistaus, @albanobattistella, …

Add a "Translators" dialog

---

.github/workflows/main.yml
src/autoupdater.cpp

The old tags all didn't start with a `v`, which is why the `v` was not included in the regex.
It is good practise to start the release tags with a `v` and it also helps to prevent false runs of the `Create Release` workflow, so I would like to add the `v` to release tags from now on.
For the `1.8.0` release we can't do that, because the update checker in existing installations wouldn't recognize the tag and the users won't get a notification dialog. We should use the tag `1.8.0` for this release.
After the release, we can revert commit 10eff85 and start using tags starting with a `v`.

Fix the update checker not detecting Birdtray releases when the tag starts with a "v"

---

src/settings.cpp
src/translations/main_de.ts
src/translations/main_en.ts
src/translations/main_it.ts
src/translations/main_nl.ts

This attempts to automatically migrate watched accounts settings from the `Sqlite` parser, which was removed in #181, to the mork parser. The user will be notified that their configuration was migrated and if there were any problems.
If you want to merge this, @gyunaev, we should do this today, because this adds new translation strings, which will break [our promise to not add any new translation starting from April 2 to the release](https://github.com/gyunaev/birdtray/issues/297#issuecomment-606891006).

Add migration from sqlite folders to mork paths

---

src/settings.cpp

The field should be called `path`, because it only contains paths to mork files now that #181 was merged.
The json settings are new and a chance for us to fix this discrepancy. #284 was merged only a week ago, apart from the two of us I don't think anybody would be impacted by this.

Rename "uri" to "path" in the settings

---

README.md
contrib/rpm/birdtray.spec

Previous PR added dependency to Qt5Svg. In many distros it requires a separate package.

Add Qt5Svg dependency information

---

.github/workflows/main.yml
src/res/com.ulduzsoft.Birdtray.desktop

This adds a step to the Github Actions CI that validates the `com.ulduzsoft.Birdtray.desktop` file using the [`desktop-file-validate`](http://manpages.ubuntu.com/manpages/bionic/man1/desktop-file-validate.1.html) tool. Closes #314.

Validate the desktop file

---

src/mailaccountdialog.cpp

ExQuilla Exchange account files are stored in the `ExQuilla` sub-folder of the profile directory. Closes #166.

Add support for finding ExQuilla Exchange accounts in the MailAccountDialog

---

installer/installer.nsi

Ok, this is a pretty bad bug. When uninstalling (and uninstalling during an upgrade), the user is presented with a choice to delete the user settings. This is unchecked by default, but because of the recent migration to JSON settings in `1.8.0`, doesn't work anymore, because the it still deletes the settings in the registry.
But that is not the bad part. The installer stores the user choices in a file at `%LOCALAPPDATA%\ulduzsoft\birdtray`. During uninstall, the folder `%LOCALAPPDATA%\ulduzsoft` and everything in it is deleted **unconditionally**. Unfortunately, since #284, the user settings are also stored in this directory and thus will also get deleted.
To fix this, when upgrading we copy the user settings to a temporary directory before we execute the uninstaller that was bundled with …

Fix always deleting user settings when uninstalling

---

contrib/rpm/birdtray.spec
src/res/com.ulduzsoft.Birdtray.appdata.xml
src/version.h

Bump the Birdtray version to 1.8.1.
Because we didn't add any new strings, we don't need to notify the active translation maintainers.
@gyunaev Please merge this pull request last.
Don't forget to push the `1.8.1` tag to the master branch after merging this.

Bump version to 1.8.1

---

CMakeLists.txt

This fixes warnings emitted by CMake when compiling Birdtray with a MSVC compiler and the `COMPILER_WARNINGS_AS_ERRORS` turned on.
The details of the policy can be found in the [CMake policy documentation](https://cmake.org/cmake/help/git-stage/policy/CMP0092.html).

Enable CMake policy CMP0092

---

CMakeLists.txt

Commit b3ae40d removed a command that told CMake to include the `CMAKE_CURRENT_BINARY_DIR`.
As it turns out, this is required for CMake versions prior to 3.8, because they store the header files generated from the `*.ui` in the `CMAKE_CURRENT_BINARY_DIR`. This is the relevant entry from the [CMake 3.8 changelog](https://cmake.org/cmake/help/v3.8/release/3.8.html#other-changes):
> When using AUTOMOC or AUTOUIC, generated moc_*, *.moc and ui_* are placed in the <CMAKE_CURRENT_BINARY_DIR>/<TARGETNAME>_autogen/include directory which is automatically added to the target’s INCLUDE_DIRECTORIES. It is therefore not necessary anymore to have CMAKE_CURRENT_BINARY_DIR in the target’s INCLUDE_DIRECTORIES.
Closes #319.

Fix compiling Birdtray with CMake versions pre 3.8

---

contrib/rpm/birdtray.spec

Some minor fixes to resolve building directly from the github release archive in order to build https://copr.fedorainfracloud.org/coprs/rnc/Birdtray/

Resolve building RPM within Fedora COPR

---

src/dialogsettings.ui
src/translations/main_de.ts
src/translations/main_en.ts
src/translations/main_es.ts
src/translations/main_it.ts
src/translations/main_nl.ts
src/translations/main_pt.ts
src/translations/main_ru.ts

This adds a new tooltip, which lets the user know that they can add any mork file by using <kbd>Ctrl</kbd>+<kbd>Shift</kbd> click. This was requested in [#166 (comment)](https://github.com/gyunaev/birdtray/issues/166#issuecomment-617152842).

Add a tooltip to the Add button in the Monitoring tab

---

src/dialogsettings.cpp

This fixes two bugs in the general tab in the settings:
* The unread notification icon choose button was selectable even tough the checkbox was not set: 
* The `Blinking speed` slider was inverted:

Fix two bugs in the general settings tab UI

---

src/utils.cpp
tests/src/test_utils.cpp

The regex was too strict, `(@name)` was not recognized as a GitHub mention. This [can be seen in the latest changelog](https://github.com/gyunaev/birdtray/pull/295#issuecomment-621337376).
We relax the regex and add some additional tests.

Fix parsing for GitHub mentions in markdown

---

.github/problem-matchers/linguist.json
.github/workflows/main.yml

This allows GitHub Actions to produce comments like the following on pull request:
It might make it easier for translators to spot errors in their files and correct them without requiring a review from us.

Add linguistic problem matchers

---

src/mailaccountdialog.cpp
src/modelaccounttree.cpp
src/trayicon.cpp
src/utils.cpp
src/utils.h

If a mail account got deleted but we were watching it, the file watcher failed, which generated a warning. That warning is added as a tool-tip to the system tray in `TrayIcon::updateIcon`, which tries to prepend the account name in front of the warning. The `parentDir.cdUp()` in `Utils::getMailAccountName` fails, because the directory does not exist, but the result was getting ignored, leading to an endless loop.
Fixes #397

Fix a hang on startup if a mail account was deleted

---

src/log.cpp

The log file was never opened. Also change the log file name to be a bit more unique and easy to find.

Fix never writing the logs on a fatal error

---

.github/workflows/main.yml

The old way generates a warning and will be removed. See [the GitHub blog post](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) for the rationale behind the change.

Use the new way of setting environment variables in GitHub Actions

---

src/dialogsettings.ui
src/translations/main_de.ts
src/translations/main_en.ts
src/translations/main_es.ts
src/translations/main_it.ts
src/translations/main_nl.ts
src/translations/main_pt.ts
src/translations/main_ru.ts
src/translations/main_sv.ts

Commit 68fff4d0b3781f9b6e77ae41ae97d570a6212e5b added a new checkbox labeled `Checkbox`. As far as I can see, it does nothing and might have been included in the commit by mistake:
This PR removes the checkbox and the corresponding translation entries.

Remove unused checkbox

---

.github/workflows/main.yml
contrib/rpm/birdtray.spec
src/autoupdater.cpp

As discussed in #298 I would like for us to use `vX.X.X` as the format for release git tags. This is the recommended and most commonly used format and it helps to prevent false positives in the GitHub Actions workflow that checks if it should create release files.
@rnc Could you please verify that my changes to the `spec` file are correct?
@gyunaev Please merge this before creating the new release. When you create the new release, please use `v1.9.0` as the git tag.

Enforce vX.X.X as the version pattern for the git tag

---

src/utils.cpp

Thunderbird started distributing 64 bit versions a while ago. This adds support for the additional Thunderbird executable location.

Search for Thunderbird in %ProgramFiles% before %ProgramFiles(x86)%

---

src/trayicon.cpp
src/unreadmonitor.cpp
src/unreadmonitor.h

Commit b789761 moved the `UnreadMonitor` thread object to itself. This caused the wait in the destructor to fail:
```
warning: QThread::wait: Thread tried to wait on itself
```
resulting in the thread being destructed while it still running and Birdtray aborting:
```
warning: QThread: Destroyed while thread is still running
```
This resolves the issue by waiting for and destroying the `UnreadMonitor` on the main thread in the `TrayIcon`.

Fix abort on Birdtray exit

---

src/autoupdater.cpp
src/autoupdater.h
src/translations/main_de.ts
src/translations/main_en.ts
src/translations/main_es.ts
src/translations/main_it.ts
src/translations/main_nl.ts
src/translations/main_pl.ts
src/translations/main_pt.ts
src/translations/main_ru.ts
src/translations/main_sv.ts
src/translations/main_tr.ts

We explicitly don't allow redirects on the initial request to the GitHub API endpoint, because we can assume that never changes.

Use the FollowRedirectsAttribute to automatically follow http redirects

---

.github/scripts/checkTranslation.py

This fixes the problem @mattuylee discovered in #446.

Allow the long language tag for the language_attr_mismatch check

---

.github/workflows/main.yml

Support for Qt5.6 ended in March 2019. The Qt team has now removed it from the [online repository](https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/), so it's no longer possible to automatically download it on the GitHub Actions runner.
This fixes the failing build.
The next course of action is to raise the minimum Qt version to 5.9. Is that ok with you, @gyunaev?

Don't test compilation with Qt5.6 anymore

---

.github/workflows/codeql-analysis.yml

This avoids the following warning which is currently generated for pull requests:
We also skip the build steps now when analyzing the Python files, because it is not needed.
@gyunaev Since this is somewhat security related, I'd like a second pair of eyes.

Update the CodeQl workflow

---

src/modelaccounttree.cpp
src/settings.cpp
src/settings.h
src/trayicon.cpp
src/unreadmonitor.cpp
src/utils.h
tests/src/test_utils.cpp

This merges the `mFolderNotificationColors` and `mFolderNotificationList` into one variable called `watchedMorkFiles`; an ordered map.
This avoids inconsistencies between the two and fixes a potential bug where we would duplicate each watched mork file in the `mFolderNotificationList` if we reloaded the settings (which is not possible at the moment, so not a problem yet).
I also added tests for the OrderedMap.
If you prefer it, I can move the OrderedMap into a new header file.

Improve how the list of watched mork files is stored at runtime

---

src/dialogsettings.cpp
src/dialogsettings.ui
src/settings.cpp
src/settings.h
src/translations/main_de.ts
src/translations/main_en.ts
src/translations/main_es.ts
src/translations/main_fr.ts
src/translations/main_it.ts
src/translations/main_nl.ts
src/translations/main_pl.ts
src/translations/main_pt.ts
src/translations/main_ru.ts
src/translations/main_sv.ts
src/translations/main_tr.ts
src/translations/main_zh_cn.ts
src/trayicon.cpp
src/trayicon.h
src/windowtools.h
src/windowtools_win.cpp
src/windowtools_x11.cpp

This adds the option to ignore all currently unread emails when showing the Thunderbird window.
It also moves all ignored emails related settings into one tab (removes the `When clicking on Birdtray icon to hide Thunderbird, reset the icon by ignoring all currently unread emails` option in the `Hiding` tab):
Further changes:
* The number of ignored emails is no longer reset to 0 if an email is marked as read and the unread email count drops below the original ignored email count. Instead, the number of ignored unread emails is simply decreased to match the number of currently unread emails.
* When Thunderbird minimized and then hidden, the `ignore unread emails when hiding` option will work now.
* Fixes a bug where the context menu would not display the number of ignored mails after …

Add option to ignore unread emails on showing Thunderbird

---

src/trayicon.cpp

Fixes #455. Also makes the total time of one blink operation the same regardless of whether fading is enabled or not.
The slowest blink (the duration of one on & off) is 3 seconds for both.

Fix inverted blinking speed when fade is enabled

---

.github/workflows/main.yml

The `jurplel/install-qt-action@v2` action seems to require this now.
This fixes the currently failing GitHub actions workflow.

Specify the exact Qt version to build with for GitHub actions

---

src/morkparser.cpp
src/morkparser.h

Shoud fix #511.
When getting the unread message count from an `.nsf` file, Birdtray currently looks for a cell named `numNewMsgs` in the first row of the table with scope ID 9E. I noticed that with my version of Thunderbird, the table with the `numNewMsgs` cell has scope ID 9E instead of 9F:
```
$ birdtray --dump-mork INBOX.msf
<...>
Table scope 9E (ns:msg:db:row:scope:dbfolderinfo:all)
Table ID 1
Row scope 9E (ns:msg:db:row:scope:dbfolderinfo:all)
Row id 1
cell flags, value 88083214
cell numMsgs, value b96
cell numNewMsgs, value 0
cell expungedBytes, value 7b1a9f
cell highWaterKey, value 2820
cell mailboxName, value INBOX
cell UIDValidity, value 4e83a32d
cell totPendingMsgs, value 0
cell version, value 1
cell forceReparse, value 0
cell fixedBadRefThreading, value 1
cell onlineName, value …
```

Make getting unread message count more reliable

---

src/windowtools_win.cpp

This seems to fix the white spaces that could be seen when restoring a Thunderbird window that was manually minimized. Hopefully fixes #487.
I tested that all normal hide/restore functionality still works as expected, but I would like to get some feedback from the submitter of #487, to make sure that this is effective, because I couldn't 100% reproduce the problem.
I will merge this, once we get some feedback.

Directly restore a hidden and minimized Thunderbird window

---

src/mailaccountdialog.cpp

On Linux, mail accounts starting with a dot are considered hidden, but we still want to show them. Fixes #522.
This was tested on Windows with a hidden mail account folder. Without these changes, the folder is not included in the account selection dialog, with these changes it is included. I assume it will also work with the folders starting with a dot on Linux.

Include hidden files when searching for profile and mail account directories

---

.github/problem-matchers/compiler.json
.github/workflows/codeql-analysis.yml
.github/workflows/main.yml
.github/workflows/translations.yml

This updates the actions used in our GitHub Actions CI. This actually seems to have speed up the CI a bit, and it gets rid of these warnings:
This meant we had to switch away from the old and now unmaintained action to create a release and switch to another. This has simplified the release workflow and it also has some cool new features like automatically generating a changelog:
Now you'll notice that there is not really anything there, it's because I run this on my fork and all the other releases there are just drafts, so the action didn't have a base line, I think. But it should work for the main repository when you create the release, it should include a list of commits since the last release, and all contributors that have committed since the last release.
The release will still be a …

Update and improve the GitHub Actions CI

---

.github/workflows/main.yml
CMakeLists.txt

This updates the newest Qt version we support to 5.15.2, and update the CI to build with it.
As shown in #434, there are some functions and features that are deprecated that are not trivial to replace.
In the interest of saving time, those deprecated warnings are just ignored for now.
This update fixes #510.

Update Qt to 5.15.2

---

src/dialogsettings.cpp
src/dialogsettings.ui
src/settings.cpp
src/settings.h
src/translations/main_de.ts
src/translations/main_el.ts
src/translations/main_en.ts
src/translations/main_es.ts
src/translations/main_fr.ts
src/translations/main_it.ts
src/translations/main_nl.ts
src/translations/main_pl.ts
src/translations/main_pt.ts
src/translations/main_ru.ts
src/translations/main_sv.ts
src/translations/main_tr.ts
src/translations/main_zh_cn.ts
src/trayicon.cpp

When Thunderbird is not running, the user can now start it by clicking the Birdtray system tray icon. Thunderbird is then optionally hidden. Two settings were added in the `Hiding` tab to control this behaviour.
For details about the feature see #420. This closes #420.

Add the ability to start Thunderbird by clicking on the system tray icon

---

src/dialogsettings.cpp
src/dialogsettings.ui
src/translations/main_de.ts
src/translations/main_el.ts
src/translations/main_en.ts
src/translations/main_es.ts
src/translations/main_fr.ts
src/translations/main_it.ts
src/translations/main_nl.ts
src/translations/main_pl.ts
src/translations/main_pt.ts
src/translations/main_ru.ts
src/translations/main_sv.ts
src/translations/main_tr.ts
src/translations/main_zh_cn.ts
src/unreadmonitor.cpp

This allows the user to change this setting in the settings dialog instead of having to go to the settings file directly. Closes #508, sort of.

Add a setting to the setting dialog for advanced/watchfiletimeout

---

CMakeLists.txt
src/dialogsettings.cpp
src/dialogsettings.ui
src/settings.cpp
src/settings.h
src/translations/main_cs.ts
src/translations/main_de.ts
src/translations/main_el.ts
src/translations/main_en.ts
src/translations/main_es.ts
src/translations/main_fr.ts
src/translations/main_it.ts
src/translations/main_nl.ts
src/translations/main_pl.ts
src/translations/main_pt.ts
src/translations/main_ru.ts
src/translations/main_sv.ts
src/translations/main_tr.ts
src/translations/main_zh_cn.ts
src/windowtools_win.cpp

This setting is only useful on Windows and allows to change the name of the process that is searched to detect if Thunderbird is running. Closes #545.
Changing the setting will take effect when saving, except for if Birdtray already found a process with the old settings.
In that case, Birdtray has to be restarted or the currently tracked process has to exit.
I think that is acceptable, since this is an advanced feature.

Add a setting to change the searched Thunderbird process name on Windows

---

CMakeLists.txt

The install layout of the OpenSSL package on CI has changed a bit. `find_package(OpenSSL)` now finds finds `.lib` files in `<...>/OpenSSL/lib`, but we need `.dll` files which are in `<...>/OpenSSL`.
To fix this we just search for the `dll` directly using `find_library` in directory returned by `find_package` and the parent directory.
I have tested that after pushing a `v1.10.1` tag the compilers were build successfully and a release was created. People have been requesting a new release for a while, do we want to notify the active translation maintainers to get the process started?

Fix not finding OpenSSL library dlls for the installer

---

.github/workflows/main.yml
installer/Utils.nsh

This pins the NSIS version, because newer version break our nsis scripts. I tested that this works on a fork.
After merging this we should either create a new version or delete the tag of the current latest version and push a new tag.
Fixes #560.

Fix Windows installer build

---

README.md

Package qt5-default does not longer exist. Instead installing all included packages makes the build process work as expected.
Debian: https://packages.debian.org/search?keywords=qt5-default&searchon=names&suite=all&section=all
Ubuntu: https://packages.ubuntu.com/search?keywords=qt5-default&searchon=names&suite=all&section=all

Updated README, qt5-default replaced

---

CMakeLists.txt

This fixes the following warning on CMake 3.X:
```
Make Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
and should hopefully prevent the following error on CMake 4, which I think should fix #615:
```
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add …
```

Bump minimum required CMake version

---

src/dialogsettings.cpp
src/dialogsettings.ui
src/settings.cpp
src/settings.h
src/translations/main_cs.ts
src/translations/main_de.ts
src/translations/main_el.ts
src/translations/main_en.ts
src/translations/main_es.ts
src/translations/main_fr.ts
src/translations/main_it.ts
src/translations/main_nl.ts
src/translations/main_pl.ts
src/translations/main_pt.ts
src/translations/main_ru.ts
src/translations/main_sv.ts
src/translations/main_tr.ts
src/translations/main_zh_cn.ts
src/trayicon.cpp

This allows to move the counter in the tray icon, **if the maximum font size is small enough that the counter can move**.
The offset is given as a positive or negative percentage, where 0% represents the center and +-100% the maximum offset.
The maximum offset takes the actual text, font size and border into account and makes sure that the number is always within the icon and never cut off.
An offset of horizontal: `100%`, vertical `-100%` and a maximum font size of `100pt` looks like this:
An offset of horizontal: `-100%`, vertical `100%` and a maximum font size of `50pt` looks like this:
The default is no offset, so this won't change existing setups.
I put the settings in the general tab:
Closes #617.
------
*This is a draft because it is build on top of the unmerged #609.*

Allow to configure an offset of the unread counter on the icon

---

.github/workflows/main.yml

This depends on #580, because with the current screenshot the verification fails with the following error:
```
src/res/com.ulduzsoft.Birdtray.appdata.xml: FAILED:
• attribute-invalid     : <screenshot> width too large [https://raw.githubusercontent.com/gyunaev/birdtray/master/screenshots/birdtray-settings.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://raw.githubusercontent.com/gyunaev/birdtray/master/screenshots/birdtray-settings.png] maximum is 900px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/gyunaev/birdtray/master/screenshots/birdtray-settings.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/gyunaev/birdtray/master/screenshots/birdtray-settings.png] …
```

Add some steps to verify the appdata metadata

---

src/windowtools_win.cpp

This hopefully fixes some weird behaviour where other windows would "freeze" until interacted with. Hopefully fixes #613. Leaving as a draft until we have confirmation or decide it's fine.

Minimize the Thunderbird window before hiding

---

src/trayicon.cpp

This fixes #625 by ignoring attempts to start Thunderbird if we already started it before.
Launching a new Thunderbird process while the other one was still running never really worked, because we would then delete the first process and immediately overwrite `mThunderbirdProcess` with a reference to the new process here:
https://github.com/gyunaev/birdtray/blob/6c31f6117dfc3b884e7f483adedb1c9a862187ec/src/trayicon.cpp#L696-L698
Deleting a `QProcess` stop the underlying process, and then `TrayIcon::tbProcessFinished` would be called, which then deleted and stopped the new process because `mThunderbirdProcess` already points to the new process:
https://github.com/gyunaev/birdtray/blob/6c31f6117dfc3b884e7f483adedb1c9a862187ec/src/trayicon.cpp#L738
I tested this locally on Windows and …

Avoid starting Thunderbird if we already started it
